presets:
  global:
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title} 
        - (duo|tri|quadri|tetra|penta|hexa|hepta|octa|ennea|deca)logy 
        - \b3-?D\b: {from: title}          
        - \bR5\b: {from: title}            
        - \bWEBSCR\b: {from: title}        
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - "{C_P}": {from: title}
        - \bFRENCH\b: {from: title}
        - \btrailer\b: {from: title}
        - "SCR": {from: title}
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.m4v'
        - '*.mp4'
        - '*.rar'
      reject:
        - '*.m2ts'
        - 'password.txt'
    pathscrub: windows
    email:
      from: uraniumserver@gmail.com
      to: blsmit5728+flexget@gmail.com
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_username: uraniumserver
      smtp_password: baseball!2
      smtp_tls: yes

  tv-global:
    include: 
      - series.yml
      - private/tl.yml                  
    content_size:
      max: 4000
      min: 20
    #content_sort:
    #  '*.rar': /Users/bsmith/PVR/tv-staging/
    exists_series:
      - "/Users/bsmith/PVR/tvshows"
    thetvdb_lookup: yes

  movie-global:
    include: 
      - private/tl.yml 
    content_size:
      max: 8000
      min: 500
    quality: 
      - 720p-1080p bluray xvid-h264 
    exists_movie:
      - /Users/bsmith/PVR/movies/
      - /Users/bsmith/PVR/torrents/
    imdb_required: yes

tasks:
  tv-shows:
    priority: 3
    preset:
      - tv-global
    series:
      settings:
        Best:
          target: 720p+ hdtv+ h264+
          timeframe: 2 hours
          quality: 480p+ dvdscr+
        Better:
          target: 480p+ dvdscr+ h264+
          timeframe: 3 hours
          quality: webrip+
        Average:
          target: 360p+ webrip+
          timeframe: 4 hours
          quality: 360p+ preair+
    download: /Users/bsmith/PVR/torrents/

  movies:
    preset: 
      - movie-global
    movie_queue: yes
    download: /Users/bsmith/PVR/torrents/

  imdb_queue:
    priority: 10 # Always run before My_Movies feeds
    preset: no_global
    interval: 2 hours
    imdb_list:
      user_id: ur34962140
      list: watchlist
    accept_all: yes
    queue_movies:
      force: no
    
  
