presets:
  global:
    free_space:
      path: /mnt/disk1/
      space: 10000
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title} 
        - (duo|tri|quadri|tetra|penta|hexa|hepta|octa|ennea|deca)logy 
        - \b3-?D\b: {from: title}          
        - \bR5\b: {from: title}            
        - \bWEBSCR\b: {from: title}        
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - "{C_P}": {from: title}
        - \bFRENCH\b: {from: title}
        - \btrailer\b: {from: title}
        - "SCR": {from: title}
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.m4v'
        - '*.mp4'
        - '*.rar'
      reject:
        - '*.m2ts'
        - 'password.txt'
    pathscrub: windows
      
  tv-global:
    include: 
      - series.yml
      - private/tl.yml                  
    content_size:
      max: 4000
      min: 20
    exists_series:
      - "/mnt/disk1/Library/TvShows/"
      - "/home/bsmith/Downloads/staging/TvShows"
    thetvdb_lookup: yes
    set:
      # Rename the "content file" to something nice
      content_filename: >
        {{ series_name|replace('/', '_')|replace(':', ' -') }} - {{ tvdb_ep_id|default(series_id) }}{% if tvdb_ep_name|default(False) %} - {{ tvdb_ep_name|replace('/', '_')|replace(':', ' -') }}{% endif %} - {{ quality }}
      label: tv
      movedone: "/mnt/disk1/Library/TvShows/{{ series_name|replace('/', '_')|replace(':', ' -') }}/{% if series_id_type == 'ep' %}Season {{ tvdb_season|default(series_season) }}/{% endif %}"
    content_sort:
      '*.rar': /home/bsmith/Downloads/completed/TvShows

  movie-global:
    include: 
      - private/tl.yml 
    content_size:
      max: 8000
      min: 500
    quality: 
      - 720p-1080p bluray xvid-h264 
    exists_movie:
      - /mnt/disk1/Library/Movies/
      - /home/bsmith/Downloads/staging/Movies/
    imdb_required: yes
    deluge:
      content_filename: >
        {{ imdb_name|replace('/', '_')|replace(':', ' -') }} ({{ imdb_year }}) - {{ quality }}
      movedone: "/mnt/disk1/Library/Movies/{{ imdb_name|replace('/', '_')|replace(':', ' -') }} ({{ imdb_year }})"
      label: movie
    content_sort:
      '*.rar': /home/bsmith/Downloads/completed/Movies

tasks:
  tv-shows:
    preset:
      - tv-global
    series:
      settings:
        Best:
          timeframe: 2 hours
          target: 720p+ hdtv+ h264+
          quality: 480p+ hdrip+ divx+
        Better:
          timeframe: 4 hours
          target: 720p+ hdtv+ h264+
          quality: 360p+ webrip+ divx+
        Average:
          timeframe: 12 hours
          target: 360p+ hdrip+
          quality: 360p+ hdrip+

  movies:
    preset: 
      - movie-global
    movie_queue: yes

  imdb_queue:
    priority: 10 # Always run before My_Movies feeds
    preset: no_global
    interval: 2 hours
    imdb_list:
      user_id: ur34962140
      list: watchlist
    accept_all: yes
    queue_movies:
      force: no
  
  local-movies:
    preset:
      - movie-global
    disable_builtins: [seen, seen_info_hash]
    disable_plugin:
      - inputs
      - exists_movie
      - seen_movies
      - regexp
      - content_size
      - torrent_alive
    movie_queue: yes
    listdir: /home/bsmith/Dropbox/Torrent/movies/
    exec:
      on_output:
        for_accepted: rm "/home/bsmith/Dropbox/Torrent/movies/{{title}}"
    accept_all: yes
    set:
      label: local-movies

  
